### ISSUE TITLE
[TrainHandler] the case of tuple outputs

### ISSUE THREAD

**Issue by jhoon-oh** [Lee-Gihun/Pytorch-OSI-setup#14]
in many cases, we extract outputs(>1) from the model.

In my case, I extract tuple output like ([feature maps], output probability).
_(line 175) topk_acc = accuracy(outputs.data, labels.data, topk=topk)_
makes error since tuple has not .data.

**Comment by kimbob13** [comment]
Could you please elaborate on this issue?
I can't understand what exactly you want.
From my understanding, you want us to modify the accuracy function, right?

**Comment by jhoon-oh** [comment]
Sometimes, we return output more than 2 from 'forward' function.
In this case, the type of output is tuple.

Then, in the line 175, 'output has not .data' error occur

**Comment by kimbob13** [comment]
I've made change in prediction attribute of TrainHandler class.
First, you should define your own prediction function.
And, the prediction functio should look like `sample_prediction(outputs, topk)`
then returns the second output of `torch.topk` function.

For example, to get top 1 and top 5 accuracy, you may make a prediction function like below.
```python
def topk_prediction(outputs, topk=(1,)):
    maxk = max(topk)
    _, preds = outputs.topk(maxk, 1, True, True)

    return preds
```

This will be noted in guide and README once our project is considered stable.
