### ISSUE TITLE
[main.py] Propose the useful experiment setting example using Config json file

### ISSUE THREAD

**Issue by raymin0223** [Lee-Gihun/Pytorch-OSI-setup#15]
As I used Pytorch-OSI-setup `main.py`, it was inconvenient that I must change some parameter setting manually on `main.py` while doing experiment on different dataset.

Therefore, I propose using `./Config/main.json` config file to change experiment setting. There will be no need to change manually on `main.py`.

Actually it is just proposing the useful setting for users. :)

**Comment by kimbob13** [comment]
This have been merged to develop branch in this commit (5fda991)
