### ISSUE TITLE
[plotter] plot seems to be dirty

### ISSUE THREAD

**Issue by raymin0223** [Lee-Gihun/Pytorch-OSI-setup#17]
Plotting has some problems like this figure.
![plot problem](https://user-images.githubusercontent.com/50742281/61035879-e9bedb80-a402-11e9-8c02-373a892418f3.PNG)

To make pretty, add **`plot_freq`** argument on utils.plotter function.
![plot problem solution](https://user-images.githubusercontent.com/50742281/61035962-1541c600-a403-11e9-8e61-59cec258a7aa.PNG)

**Comment by kimbob13** [comment]
This issue is merged in 3defa00

**Comment by kimbob13** [comment]
This issue have been merged in 3defa00
