### ISSUE TITLE
aux.py naming issue

### ISSUE THREAD

**Issue by kimbob13** [Lee-Gihun/Pytorch-OSI-setup#21]
In Windows, the file name **aux** is reserved for OS,
so I can't see this file in my local desktop.

![aux_py_issue](https://user-images.githubusercontent.com/26755098/61259891-1b46f680-a7b7-11e9-9d1c-38e96afc87a6.png)

Therefore, we should consider chainging the name of this file.

**Comment by raymin0223** [comment]
Oh.. Let's change name to `config_loader.py`!

**Comment by kimbob13** [comment]
This issue has been resolved in ebdc0c9
