### ISSUE TITLE
[ImportError] attempted relative import with no known parent package

### ISSUE THREAD

**Issue by raymin0223** [Lee-Gihun/Pytorch-OSI-setup#9]
When I copy all files to another server and run `guide.ipynb`, **`ImportError: attempted relative import with no known parent package`** occur.
It derives from `from .data_utils.autoaugment import CIFAR10Policy` line in `data_setter.py` of develop branch.

But if I use absolute import path `from data_utils.autoaugment import CIFAR10Policy` without **[.]**, no ImportError occur.
It will be helpful to give package path INFO.

**Comment by Lee-Gihun** [comment]
@kimbob13 needs to be solve this first. Simply, following import manner cause error.

```from data_setter import cifar_10_setter```

It happend just after the commit handling package paths

**Comment by kimbob13** [comment]
This issue has resolved in 53c0914
